whatis("Name:        Stata")
whatis("Version:     17")
whatis("Category:    applications, statistics, licensed")
whatis("Keywords:    application, statistics")
whatis("URL:         https://www.stata.com/why-use-stata")
whatis("Description: Integrated statistical software package for data analysis, data management, and graphics.")
prepend_path("PATH","/share/sw/restricted/stata/17")
set_alias("stata", "/share/sw/restricted/stata/17/stata-se")
