whatis("Name:        Anaconda3")
whatis("Version:     5.2")
whatis("Category:    applications, interpreters, languagesx")
whatis("Keywords:    application, interpreter, language")
whatis("URL:         https://www.anaconda.com/download/#linux")
whatis("Description: Python 3 distribution")

prepend_path("PATH","/share/sw/open/anaconda/3/bin")
prepend_path("PATH","/share/sw/open/anaconda/3/condabin/share/sw/open/anaconda/3/condabin")
prepend_path("CPATH","/usr/include")
prepend_path("CPATH","/usr/include/x86_64-linux-gnu")
setenv("CONDA_SHLVL","1")
setenv("CONDA_EXE","/share/sw/open/anaconda/3/bin/conda")
setenv("GDAL_DATA","/share/sw/open/anaconda/3/share/gdal")
setenv("GPROF","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-gprof")
setenv("GXX","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-g++")
setenv("LD_GOLD","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-ld.gold")
setenv("DEBUG_CPPFLAGS","-D_DEBUG -D_FORTIFY_SOURCE","2 -Og")
setenv("DEBUG_CFLAGS","-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe")
setenv("GCC_NM","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-gcc-nm")
setenv("CPL_ZIP_ENCODING","UTF-8")
setenv("CONDA_PREFIX","/share/sw/open/anaconda/3")
setenv("GCC_RANLIB","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib")
setenv("CFLAGS","-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe")
setenv("GCC_AR","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-gcc-ar")
setenv("CC","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-cc")
setenv("READELF","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-readelf")
setenv("PROJ_LIB","/share/sw/open/anaconda/3/share/proj")
setenv("CXXFLAGS","-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe")
setenv("STRIP","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-strip")
setenv("DEBUG_FFLAGS","-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -pipe")
setenv("OBJCOPY","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-objcopy")
setenv("_CONDA_PYTHON_SYSCONFIGDATA_NAME","_sysconfigdata_x86_64_conda_cos6_linux_gnu")
setenv("LIBARCHIVE","/share/sw/open/anaconda/3/lib/libarchive")
setenv("ADDR2LINE","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-addr2line")
setenv("CONDA_PYTHON_EXE","/share/sw/open/anaconda/3/bin/python")
setenv("_CONDA_SET_LIBARCHIVE","LIBARCHIVE")
setenv("HOST","x86_64-conda_cos6-linux-gnu")
setenv("F77","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-gfortran")
setenv("FORTRANFLAGS","-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe")
setenv("RANLIB","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-ranlib")
setenv("OBJDUMP","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-objdump")
setenv("AS","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-as")
setenv("AR","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-ar")
setenv("GFORTRAN","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-gfortran")
setenv("CONDA_BACKUP_HOST","x86_64-conda_cos6-linux-gnu")
setenv("DEBUG_FORTRANFLAGS","-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -pipe")
setenv("FC","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-gfortran")
setenv("NM","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-nm")
setenv("CONDA_PROMPT_MODIFIER","(base)") 
setenv("DEBUG_CXXFLAGS","-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe")
setenv("CXX","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-c++")
setenv("UDUNITS2_XML_PATH","/share/sw/open/anaconda/3/share/udunits/udunits2.xml")
setenv("CXXFILT","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-c++filt")
setenv("GEOTIFF_CSV","/share/sw/open/anaconda/3/share/epsg_csv")
setenv("ELFEDIT","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-elfedit")
setenv("FFLAGS","-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe")
setenv("CPPFLAGS","-DNDEBUG -D_FORTIFY_SOURCE","2 -O2")
setenv("STRINGS","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-strings")
setenv("F95","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-f95")
setenv("RSTUDIO_WHICH_R","/share/sw/open/anaconda/3/bin/R")
setenv("LDFLAGS","-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now")
setenv("GCC","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-gcc")
setenv("CONDA_DEFAULT_ENV","base")
setenv("SIZE","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-size")
setenv("CPP","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-cpp")
setenv("LD","/share/sw/open/anaconda/3/bin/x86_64-conda_cos6-linux-gnu-ld")

prepend_path("PYTHONPATH","/share/sw/open/anaconda/3/bin")
